steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/backend', '.']

  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/backend']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/backend'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--set-env-vars'
      - 'NODE_ENV=production,PORT=8080,DB_SOCKET_PATH=/cloudsql/delta-entity-447812-p2:us-central1:delta-entity-447812-db'
      - '--add-cloudsql-instances'
      - 'delta-entity-447812-p2:us-central1:delta-entity-447812-db'
      - '--service-account'
      - 'nifya-orchestration@delta-entity-447812-p2.iam.gserviceaccount.com'
      - '--allow-unauthenticated'
      - '--min-instances'
      - '1'
      - '--port'
      - '8080'
      - '--timeout'
      - '300s'
      - '--cpu'
      - '1'
      - '--memory'
      - '512Mi'
      - '--execution-environment'
      - 'gen2'
      - '--vpc-connector'
      - 'projects/delta-entity-447812-p2/locations/us-central1/connectors/vpc-connector'
      - '--vpc-egress'
      - 'all-traffic'

images:
  - 'gcr.io/$PROJECT_ID/backend'

options:
  logging: CLOUD_LOGGING_ONLY