steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/backend', '.']

  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/backend']

  # Deploy to Cloud Run with VPC connector
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/backend'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--vpc-connector'
      - 'projects/delta-entity-447812-p2/locations/us-central1/connectors/backend-connector'
      - '--vpc-egress'
      - 'private-ranges-only'
      - '--set-env-vars'
      - 'NODE_ENV=production,DB_HOST=10.77.0.3'
      - '--allow-unauthenticated'
      - '--no-cpu-throttling'
      - '--min-instances'
      - '1'
      - '--execution-environment'
      - 'gen2'

images:
  - 'gcr.io/$PROJECT_ID/backend'

options:
  logging: CLOUD_LOGGING_ONLY