import { z } from 'zod';
import dotenv from 'dotenv';
import { SecretManagerServiceClient } from '@google-cloud/secret-manager';
import logger from '../utils/logger.js';

dotenv.config();

const secretManagerClient = new SecretManagerServiceClient();

async function getSecret(name: string): Promise<string> {
  try {
    const [version] = await secretManagerClient.accessSecretVersion({
      name: `projects/delta-entity-447812-p2/secrets/${name}/versions/latest`,
    });
    return version.payload?.data?.toString() || '';
  } catch (error) {
    logger.warn(`Failed to fetch secret ${name} from Secret Manager, falling back to environment variable`, error);
    return process.env[name] || '';
  }
}

export const configSchema = z.object({
  PORT: z.string().default('3000'),
  NODE_ENV: z.enum(['development', 'production', 'test']).default('development'),
  AUTH_SERVICE_URL: z.string().url(),
  JWT_SECRET: z.string().min(32),
  CORS_ORIGIN: z.string().url(),
  RATE_LIMIT_WINDOW_MS: z.string().transform(Number).default('900000'),
  RATE_LIMIT_MAX: z.string().transform(Number).default('100')
});

const dbConfigSchema = z.object({
  DB_HOST: z.string(),
  DB_PORT: z.number(),
  DB_NAME: z.string(),
  DB_USER: z.string(),
  DB_PASSWORD: z.string(),
  DB_INSTANCE_CONNECTION_NAME: z.string()
});

export async function initConfig() {
  const [
    dbHost,
    dbPort,
    dbName,
    dbUser,
    dbPassword,
    dbInstance,
  ] = await Promise.all([
    getSecret('DB_HOST'),
    getSecret('DB_PORT'),
    getSecret('DB_NAME'),
    getSecret('DB_USER'),
    getSecret('DB_PASSWORD'),
    getSecret('DB_INSTANCE_CONNECTION_NAME'),
  ]);

  const envConfig = configSchema.parse(process.env);
  
  const dbConfig = dbConfigSchema.parse({
    DB_HOST: dbHost || process.env.DB_HOST,
    DB_PORT: parseInt(dbPort || process.env.DB_PORT || '5432', 10),

  return {
    ...config,
    DB_HOST: dbHost,
    DB_PORT: parseInt(dbPort, 10),
    DB_NAME: dbName,
    DB_USER: dbUser,
    DB_PASSWORD: dbPassword,
    DB_INSTANCE_CONNECTION_NAME: dbInstance,
  };
}

export type Config = Awaited<ReturnType<typeof initConfig>>;

let config: Config | null = null;

export async function getConfig(): Promise<Config> {
  if (!config) {
    config = await initConfig();
  }
  return config;
}
